src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $product_name;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $product_author;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $product_desc;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    private $product_cover;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=2)
     */
    private $product_price;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_stock;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    private $product_category;

    /**
     * @ORM\OneToMany(targetEntity=Content::class, mappedBy="product", orphanRemoval=true)
     */
    private $contents;

    /**
     * @ORM\OneToMany(targetEntity=ContentOrder::class, mappedBy="product", orphanRemoval=true)
     */
    private $contentOrders;

    public function __construct()
    {
        $this->contents = new ArrayCollection();
        $this->contentOrders = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->product_name . $this->product_category . $this->product_price;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(string $product_name): self
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getProductAuthor(): ?string
    {
        return $this->product_author;
    }

    public function setProductAuthor(string $product_author): self
    {
        $this->product_author = $product_author;

        return $this;
    }

    public function getProductDate(): ?int
    {
        return $this->product_date;
    }

    public function setProductDate(int $product_date): self
    {
        $this->product_date = $product_date;

        return $this;
    }

    public function getProductDesc(): ?string
    {
        return $this->product_desc;
    }

    public function setProductDesc(?string $product_desc): self
    {
        $this->product_desc = $product_desc;

        return $this;
    }

    public function getProductCover(): ?string
    {
        return $this->product_cover;
    }

    public function setProductCover(?string $product_cover): self
    {
        $this->product_cover = $product_cover;

        return $this;
    }

    public function getProductPrice(): ?string
    {
        return $this->product_price;
    }

    public function setProductPrice(string $product_price): self
    {
        $this->product_price = $product_price;

        return $this;
    }

    public function getProductStock(): ?int
    {
        return $this->product_stock;
    }

    public function setProductStock(int $product_stock): self
    {
        $this->product_stock = $product_stock;

        return $this;
    }

    public function getProductCategory(): ?string
    {
        return $this->product_category;
    }

    public function setProductCategory(?string $product_category): self
    {
        $this->product_category = $product_category;

        return $this;
    }

    /**
     * @return Collection|Content[]
     */
    public function getContents(): Collection
    {
        return $this->contents;
    }

    public function addContent(Content $content): self
    {
        if (!$this->contents->contains($content)) {
            $this->contents[] = $content;
            $content->setProduct($this);
        }

        return $this;
    }

    public function removeContent(Content $content): self
    {
        if ($this->contents->removeElement($content)) {
            // set the owning side to null (unless already changed)
            if ($content->getProduct() === $this) {
                $content->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ContentOrder[]
     */
    public function getContentOrders(): Collection
    {
        return $this->contentOrders;
    }

    public function addContentOrder(ContentOrder $contentOrder): self
    {
        if (!$this->contentOrders->contains($contentOrder)) {
            $this->contentOrders[] = $contentOrder;
            $contentOrder->setProduct($this);
        }

        return $this;
    }

    public function removeContentOrder(ContentOrder $contentOrder): self
    {
        if ($this->contentOrders->removeElement($contentOrder)) {
            // set the owning side to null (unless already changed)
            if ($contentOrder->getProduct() === $this) {
                $contentOrder->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/ProductController.php
<?php
	namespace App\Controller;
	use App\Entity\Product;
	use App\Repository\ProductRepository;
	use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
	use Symfony\Component\HttpFoundation\Request;
	use Symfony\Component\HttpFoundation\Response;
	use Symfony\Component\Routing\Annotation\Route;

	class ProductController extends AbstractController {
		/**
		* @Route("/mangas/{category}", name="catalog")
		*/
		public function catalog(Request $request, ProductRepository $productRepository): Response {
			$categories = $productRepository->searchCategory();
			$category = $request->get("category");
			$offset = max(0, $request->query->getInt('offset', 0));
			$paginator = $productRepository->getProductPaginator($offset, $category);
			return $this->render("product/catalog.html.twig", [
				"products" => $paginator,
				"offset" => $offset,
				"previous" => $offset - ProductRepository::PAGINATOR_PER_PAGE,
				"next" => min(count($paginator), $offset + ProductRepository::PAGINATOR_PER_PAGE),
				"categories" => $categories,
				"filter" => $category,
			]);
		}
		/**
		* @Route("/manga/{id}", name="product")
		*/
		public function product(Product $product): Response {
			return $this->render("product/product.html.twig", [
				"product" => $product
			]);
		}
		/**
		* @Route("/recherche/{query}", name="search")
		*/
		public function search(ProductRepository $productRepository, Request $request): Response {
			$query = $request->get("query");
			$products = $productRepository->searchName($query);
			return $this->render("home/search.html.twig", [
				"query" => $query,
				"products" => $products
			]);
		}
	}
?>

templates/product/catalog.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{% if filter == "all" %}
		Notre catalogue
	{% else %}
		Nos {{filter}}s
	{% endif %} • Yellow
{% endblock %}
{% block body %}
	<link rel="stylesheet" href="/css/catalog.css">
	<link rel="stylesheet" href="/css/home.css">
	<main>
		<h1>
			{% if filter == "all" %}
				Tous nos mangas
			{% else %}
				Nos {{filter}}s
			{% endif %}
		</h1>
		<div class="form-group">
			<form method="POST" id="form-search-by-category">
				<label for="category">Filtrer par catégorie :</label>
				<select id="select-category" onchange="filterByCategory()">
					<option value="all" selected>(Tout)</option>
					{% for category in categories %}
						{% if category == filter %}
							<option value="{{category}}" selected>{{category}}</option>
						{% else %}
							<option value="{{category}}">{{category}}</option>
						{% endif %}
					{% endfor %}
				</select>
			</form>
		</div>
		<!-- Searchbar -->
		<div class="searchbar">
			<form method="POST" class="search-form">
				<input class="search-input" id="search" name="query" placeholder="Rechercher un produit">
				<button type="submit" id="btn-search" class="btn-search">
					<ion-icon name="search-outline" size="large"></ion-icon>
				</button>
			</form>
			<script>
				// Send form with search query
				document.querySelector(".search-form").addEventListener("submit", e => {
					e.preventDefault();
					const query = e.target.children[0].value;
					if (query.length > 0) {
						const url = "{{path('search', {query: 'search-value'})}}"
							.replace("search-value", e.target.children[0].value);
						e.target.setAttribute("action", url);
						e.target.submit()
					}
				})
			</script>
		</div>
		<div class="catalog-container">
			{% for product in products %}
				<a href="{{path('product', {id: product.id})}}" class="product" style="background-image: url(/images/cover/{{product.productCover}}.jpg)">
					<div class="product-footer">
						<div class="product-primary-info">
							<div class="product-info">
								<span class="product-title">{{product.productName}}</span>
								<div class="product-subtitle">
									{{product.productAuthor}} •<span class="product-date">{{product.productDate}}</span>
								</div>
							</div>
							<div class="product-price">{{product.productPrice}}€</div>
						</div>
						<div class="product-desc">{{product.productDesc}}</div>
					</div>
				</a>
			{% endfor %}
		</div>
		<div class="page-container">
		{% if previous >= 0 %}
		<a href="{{ path('catalog', { offset: previous, category: 'all' }) }}" class="page">
			<ion-icon name="chevron-back"></ion-icon> 
		</a>
		{% if offset == 10 %}
		2/3
		{% endif %}
		{% if offset == 20 %}
		3/3
		{% endif %}
		{% endif %}
		{% if next < products|length %}
		{% if offset == 0 %}
		1/3
		{% endif %}
		<a href="{{ path('catalog', { offset: next, category: 'all' }) }}" class="page">
			<ion-icon name="chevron-forward"></ion-icon>
		</a>
		{% endif %}
		</div>
	</main>
	<script>
		const filterByCategory = () => {
			const form = document.querySelector("#form-search-by-category"),
				url = "{{path('catalog', {category: 'value'})}}"
					.replace("value", form.querySelector("#select-category").value);
			form.setAttribute("action", url);
			form.submit()
		}
	</script>
{% endblock %}

templates/product/product.html.twig
{% extends "base.html.twig" %}

{% block title %}{{product.productName}} ({{product.productCategory}}) • Yellow{% endblock %}
{% block body %}
	<link rel="stylesheet" href="/css/product.css">
	<style>
		@media screen and (max-width: 1000px) {
			.cover::before {background-image: url(/images/cover/{{product.productCover}}.jpg)}
		}
	</style>
	<main>
		<!-- Back to catalog link -->
		<a href="{{path('catalog', {category: 'all'})}}" class="back">
			<ion-icon name="chevron-back-outline"></ion-icon>
			Retour au catalogue
		</a>
		<!-- Product container -->
		<div class="product-container">
			<div class="cover">
				<img src="/images/cover/{{product.productCover}}.jpg" alt="Image de couverture">
			</div>
			<div class="informations">
				<!-- Product title & price -->
				<h1 class="title">
					<span class="product-title">{{product.productName}}</span>
					<span class="product-price">{{product.productPrice}}€</span>
				</h1>
				<div class="blank"></div>
				<!-- Actions -->
				<div class="actions">
					{% if product.productStock > 0 and product.productStock < 10 %}
						<span class="iconify product-stock valid" data-icon="gg:danger"></span>
						<span class="product-stock valid">Plus que {{product.productStock}} en stock</span>
						<!-- Add to basket link -->
						<a href="{{path('add-to-basket', {id: product.id})}}" class="add-to-basket">
							<ion-icon name="bag-add-outline"></ion-icon>
							Ajouter au panier
						</a>
					{% elseif product.productStock > 5 %}
						<span class="product-stock valid">En stock</span>
						<!-- Add to basket link -->
						<a href="{{path('add-to-basket', {id: product.id})}}" class="add-to-basket">
							<ion-icon name="bag-add-outline"></ion-icon>
							Ajouter au panier
						</a>
					{% else %}
						<span class="product-stock invalid">Rupture de stock</span>
					{% endif %}
				</div>
				<div class="blank"></div>
				<!-- Product author & date (year) -->
				<div class="product-author">
					Ecrit par {{product.productAuthor}} <span class="product-date">• {{product.productDate}}</span>
				</div>
				<!-- Product category name -->
				<div class="product-category">
					<span>{{product.productCategory}}</span> • 
					<a href="{{path('catalog', {category: product.productCategory})}}">En voir plus de ce type</a>
				</div>
				<!-- Product description -->
				<div class="product-desc">{{product.productDesc}}</div>
			</div>
		</div>
	</main>
	<script src="https://code.iconify.design/2/2.1.1/iconify.min.js"></script>
{% endblock %}