src/Entity/Basket.php
<?php

namespace App\Entity;

use App\Repository\BasketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BasketRepository::class)
 */
class Basket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Customer::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $customer;

    /**
     * @ORM\OneToMany(targetEntity=Content::class, mappedBy="basket", orphanRemoval=true)
     */
    private $contents;

    public function __construct()
    {
        $this->contents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return Collection|Content[]
     */
    public function getContents(): Collection
    {
        return $this->contents;
    }

    public function addContent(Content $content): self
    {
        if (!$this->contents->contains($content)) {
            $this->contents[] = $content;
            $content->setBasket($this);
        }

        return $this;
    }

    public function removeContent(Content $content): self
    {
        if ($this->contents->removeElement($content)) {
            // set the owning side to null (unless already changed)
            if ($content->getBasket() === $this) {
                $content->setBasket(null);
            }
        }

        return $this;
    }
}

src/Entity/Content.php
<?php

namespace App\Entity;

use App\Repository\ContentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContentRepository::class)
 */
class Content
{
    /**
    * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $content_product_quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Basket::class, inversedBy="contents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $basket;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="contents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContentProductQuantity(): ?int
    {
        return $this->content_product_quantity;
    }

    public function setContentProductQuantity(int $content_product_quantity): self
    {
        $this->content_product_quantity = $content_product_quantity;

        return $this;
    }

    public function getBasket(): ?Basket
    {
        return $this->basket;
    }

    public function setBasket(?Basket $basket): self
    {
        $this->basket = $basket;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $product_name;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $product_author;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $product_desc;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    private $product_cover;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=2)
     */
    private $product_price;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_stock;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    private $product_category;

    /**
     * @ORM\OneToMany(targetEntity=Content::class, mappedBy="product", orphanRemoval=true)
     */
    private $contents;

    /**
     * @ORM\OneToMany(targetEntity=ContentOrder::class, mappedBy="product", orphanRemoval=true)
     */
    private $contentOrders;

    public function __construct()
    {
        $this->contents = new ArrayCollection();
        $this->contentOrders = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->product_name . $this->product_category . $this->product_price;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(string $product_name): self
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getProductAuthor(): ?string
    {
        return $this->product_author;
    }

    public function setProductAuthor(string $product_author): self
    {
        $this->product_author = $product_author;

        return $this;
    }

    public function getProductDate(): ?int
    {
        return $this->product_date;
    }

    public function setProductDate(int $product_date): self
    {
        $this->product_date = $product_date;

        return $this;
    }

    public function getProductDesc(): ?string
    {
        return $this->product_desc;
    }

    public function setProductDesc(?string $product_desc): self
    {
        $this->product_desc = $product_desc;

        return $this;
    }

    public function getProductCover(): ?string
    {
        return $this->product_cover;
    }

    public function setProductCover(?string $product_cover): self
    {
        $this->product_cover = $product_cover;

        return $this;
    }

    public function getProductPrice(): ?string
    {
        return $this->product_price;
    }

    public function setProductPrice(string $product_price): self
    {
        $this->product_price = $product_price;

        return $this;
    }

    public function getProductStock(): ?int
    {
        return $this->product_stock;
    }

    public function setProductStock(int $product_stock): self
    {
        $this->product_stock = $product_stock;

        return $this;
    }

    public function getProductCategory(): ?string
    {
        return $this->product_category;
    }

    public function setProductCategory(?string $product_category): self
    {
        $this->product_category = $product_category;

        return $this;
    }

    /**
     * @return Collection|Content[]
     */
    public function getContents(): Collection
    {
        return $this->contents;
    }

    public function addContent(Content $content): self
    {
        if (!$this->contents->contains($content)) {
            $this->contents[] = $content;
            $content->setProduct($this);
        }

        return $this;
    }

    public function removeContent(Content $content): self
    {
        if ($this->contents->removeElement($content)) {
            // set the owning side to null (unless already changed)
            if ($content->getProduct() === $this) {
                $content->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ContentOrder[]
     */
    public function getContentOrders(): Collection
    {
        return $this->contentOrders;
    }

    public function addContentOrder(ContentOrder $contentOrder): self
    {
        if (!$this->contentOrders->contains($contentOrder)) {
            $this->contentOrders[] = $contentOrder;
            $contentOrder->setProduct($this);
        }

        return $this;
    }

    public function removeContentOrder(ContentOrder $contentOrder): self
    {
        if ($this->contentOrders->removeElement($contentOrder)) {
            // set the owning side to null (unless already changed)
            if ($contentOrder->getProduct() === $this) {
                $contentOrder->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/BasketController.php
<?php
	namespace App\Controller;
	use App\Entity\Basket;
	use App\Entity\Content;
	use App\Entity\ContentOrder;
	use App\Entity\Order;
	use App\Entity\Product;
	use App\Repository\BasketRepository;
	use App\Repository\ContentRepository;
	use App\Repository\ContentOrderRepository;
	use App\Repository\CustomerRepository;
	use App\Repository\OrderRepository;
	use App\Repository\ProductRepository;
	use App\Session\Session;
	use Doctrine\ORM\EntityManagerInterface;
	use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
	use Symfony\Component\HttpFoundation\Request;
	use Symfony\Component\HttpFoundation\Response;
	use Symfony\Component\Routing\Annotation\Route;

	class BasketController extends AbstractController {
		/**
		 * @Route("/panier", name="basket")
		 */
		public function basket(BasketRepository $basketRepository, ContentRepository $contentRepository, ProductRepository $productRepository, Session $session): Response {
			// Display user basket content
			if ($session->get("customer")) {
				// There is an active session
				// Get basket content
				$basket = $basketRepository->findBy(array("customer" => $session->get("customer")["id"]))[0];
				$content = $contentRepository->findBy(array("basket" => $basket->getId()));
				$products = [];
				for ($i = 0; $i < count($content); $i++) {
					array_push($products, $productRepository->findBy(array("id" => $content[$i]->getProduct()))[0]);
				}
				// Render the basket page with the current user basket
				return $this->render("basket/index.html.twig", [
					"content" => $content,
					"items" => $products
				]);
			} else return $this->redirectToRoute("login");
		}
		/**
		* @Route("/ajouteraupanier/{id}", name="add-to-basket")
		*/
		public function addToBasket(
			Request $request,
			EntityManagerInterface $entityManager,
			ProductRepository $productRepository,
			BasketRepository $basketRepository,
			ContentRepository $contentRepository,
			Session $session
		): Response {
			// Add product to customer basket
			if ($session->get("customer")) {
				// There is an active session
				$basket = $basketRepository->findBy(array("customer" => $session->get("customer")["id"]))[0];
				$product = $productRepository->findBy(array("id" => $request->get("id")))[0];
				$content = $contentRepository->findBy(array(
					"basket" => $basket->getId(),
					"product" => $request->get("id")
				));
				if (array($content) && count($content) == 1) {
					// The product is already in the basket
					// Increment product quantity by 1
					$content[0]->setContentProductQuantity($content[0]->getContentProductQuantity() + 1);
				} else {
					// Create basket content
					$content = new Content();
					$content->setBasket($basket);
					$content->setProduct($product);
					$content->setContentProductQuantity(1);
					$entityManager->persist($content);
				}
				// Commit changes
				$entityManager->flush();
				// Redirect to the customer basket
				return $this->redirectToRoute("basket");
			} else return $this->redirectToRoute("login");
		}
		/**
		* @Route("/quantite/{id}/{quantity}", name="edit-quantity")
		*/
		public function editQuantity(Request $request, EntityManagerInterface $entityManager, ContentRepository $contentRepository): Response {
			// Remove product from customer basket
			$quantity = $request->get("quantity");
			if ((int)$quantity && $quantity > 0 && $quantity <= 10) {
				// Valid parameter
				$content = $contentRepository->findBy(array("id" => $request->get("id")))[0];
				$content->setContentProductQuantity($request->get("quantity"));
				// Commit changes
				$entityManager->flush();
			}
			// Redirect to the customer basket
			return $this->redirectToRoute("basket");
		}
		/**
		* @Route("/supprimerdupanier/{id}", name="remove-from-basket")
		*/
		public function removeFromBasket(Request $request, EntityManagerInterface $entityManager, ContentRepository $contentRepository): Response {
			// Remove product from customer basket
			$content = $contentRepository->findBy(array("id" => $request->get("id")));
			foreach ($content as $item) {
				$entityManager->remove($item);
			}
			// Commit changes
			$entityManager->flush();
			// Redirect to the customer basket
			return $this->redirectToRoute("basket");
		}
		/**
		* @Route("/commander", name="make-order")
		*/
		public function makeOrder(
			Session $session,
			BasketRepository $basketRepository,
			ContentRepository $contentRepository,
			ContentOrderRepository $contentOrderRepository,
			CustomerRepository $customerRepository,
			ProductRepository $productRepository,
			EntityManagerInterface $entityManager
		): Response {
			// Order basket content as session user
			if ($session->get("customer")) {
				// There is an active session
				// Create a new order
				$order = new Order();
				// Set order customer ID
				$customer = $customerRepository->findBy(array("id" => $session->get("customer")["id"]))[0];
				$order->setCustomer($customer);
				// Set order total price
				$basket = $basketRepository->findBy(array("customer" => $customer->getId()))[0];
				$contents = $contentRepository->findBy(array("basket" => $basket->getId()));
				if (count($contents) > 0) {
					// The basket is not empty, can make order
					$ordererror = 0;
					$total = 0;
					$ordererrorproducts = [];
					foreach ($contents as $content) {
						$product = $productRepository->findBy(array("id" => $content->getProduct()))[0];
						$total += $product->getProductPrice() * $content->getContentProductQuantity();
						// Create new order item
						$contentOrder = new ContentOrder();
						$contentOrder->setOrder($order);
						$contentOrder->setQuantity($content->getContentProductQuantity());

						$pouet = $product->getProductStock()-$content->getContentProductQuantity();
						if ($pouet < 0){
							$ordererror = 1;
							array_push($ordererrorproducts, $product);
						} else{
							$product->setProductStock($pouet);
							$contentOrder->setProduct($content->getProduct());
							$entityManager->persist($contentOrder);
							// Empty basket by removing its content
							$entityManager->remove($content);
						}
					}

					if ($ordererror == 0){
						$order->setOrderTotal($total);
						// Set order status
						$order->setOrderStatus(0);
						$entityManager->persist($order);
						// Commit changes
						$entityManager->flush();
					}

					// Render the thank you page
					return $this->render("basket/thanks.html.twig", [
						"orderError" => $ordererror,
						"orderErrorProducts" => $ordererrorproducts,
						"total" => $total
					]);
				} else {
					// The basket is empty, redirection to the basket
					return $this->redirectToRoute("basket");
				}
			} else return $this->redirectToRoute("login");
		}
	}
?>

templates/basket/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Panier • Yellow{% endblock %}

{% block body %}
	<link rel="stylesheet" href="/css/basket.css">
	<main>
		<h1>Mon panier</h1>
		<div class="basket-container">
			<div class="basket">
				{% if items|length == 0 %}
					<div class="basket-empty">
						<img src="/images/coffee.png">
						<h2>Votre panier est vide !</h2>
						<a href="{{path('catalog', {category: 'all'})}}" class="goto">
							Accédez à notre catalogue
							<ion-icon name="arrow-forward-circle-outline"></ion-icon>
						</a>
					</div>
				{% else %}
					<h2>Contenu du panier</h2>
					<span class="basket-count">
						{{items|length}}
						{% if items|length > 1 %}
							items
						{% else %}
							item
						{% endif %}
					</span>
					<ul class="basket-content">
						{% for item in items %}
							<li>
								<div class="product-info-container">
									<img src="/images/cover/{{item.productCover}}.jpg" class="product-cover">
									<div class="product-info">
										<a href="{{path('product', {id: item.id})}}" class="product-title" title="Voir le manga" aria-label="Voir le manga">{{item.productName}}</a>
										<span class="product-subtitle">
											<span class="product-author">{{item.productAuthor}}</span> • 
											<span class="product-date">{{item.productDate}}</span>
										</span>
										<span class="product-price">{{item.productPrice}}€</span>
									</div>
								</div>
								<div class="product-actions">
									<form method="POST" class="product-quantity" data-item="{{content[loop.index - 1].id}}">
										Quantité
										<select id="edit-quantity" onchange="editQuantity(this)">
											{% set quantity = content[loop.index - 1].contentProductQuantity %}
											{% for i in range(1, 10) %}
												{% if quantity == i %}
													<option value="{{i}}" selected>{{i}}</option>
												{% else %}
													<option value="{{i}}">{{i}}</option>
												{% endif %}
											{% endfor %}
										</select>
									</form>
									<a href="{{path('remove-from-basket', {id: content[loop.index - 1].id})}}" class="remove-from-basket">
										<ion-icon name="trash-outline"></ion-icon>
										Retirer
									</a>
								</div>
							</li>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
			{% if items|length > 0 %}
				<div class="recap">
					<h2>Prix total (TTC) :</h2>
					<div class="total-price">
						{% set total = 0 %}
						{% for item in items %}
							{% set total = total + (item.productPrice * content[loop.index - 1].contentProductQuantity) %}
						{% endfor %}
						{{total|number_format(2)}}€
					</div>
					<a href="{{path('catalog', {category: 'all'})}}" class="continue-browsing">
						<ion-icon name="cart-outline"></ion-icon>
						Continuer vos achats
					</a>
					<a href="{{path('make-order')}}" id="validate-basket">
						<ion-icon name="bag-check-outline"></ion-icon>
						Passer commande
					</a>
				</div>
			{% endif %}
		</div>
	</main>
	<script>
		const editQuantity = select => {
			const form = select.parentNode,
				url = "{{path('edit-quantity', {id: 'item', quantity: 'value'})}}"
					.replace("item", form.dataset.item)
					.replace("value", select.value);
			form.setAttribute("action", url);
			form.submit()
		}
	</script>
{% endblock %}

templates/basket/thanks.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{% if orderError == 0 %}
		Merci de votre achat !
	{% elseif orderError == 1 %}
		Commande refusée
	{% endif %} • Yellow
{% endblock %}
{% block body %}
	<link rel="stylesheet" href="/css/basket.css">
	<link rel="stylesheet" href="/css/thanks.css">
	<main class="center">
		{% if orderError == 0 %}
			<img src="images/chopper.png">
			<h1 class="thank-you">Merci !</h1>
			<p class="order-info">Total de votre commande : {{total|number_format(2)}}€</p>
			<a href="{{path('account')}}" class="goto">
				Accéder à mon compte
				<ion-icon name="arrow-forward-circle-outline"></ion-icon>
			</a>
		{% elseif orderError == 1 %}
			<img class="sadchopper" src="images/sadchopper.png">
			<h1 class="thank-you">Stock insuffisant</h1>
			<p class="error-info">Nous sommes désolés, les produits suivants ne peuvent pas être commandés :</p>
			<ul class="product-list">
				{% for product in orderErrorProducts %}
					<li>
						<div class="content">
							<img src="/images/cover/{{product.productCover}}.jpg" alt="Image de couverture">
							<span class="count">{{product.productStock}}x</span>{{product.productName}}
						</div>
						<div class="actions">
							<a href="{{path('product', {id: product.id})}}">Voir le produit</a>
						</div>
					</li>
				{% endfor %}
			</ul>
		{% endif %}
	</main>
{% endblock %}